# fly.toml app configuration file generated for matchmakingsignalingserver on 2023-08-25T09:05:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matchmakingsignalingserver"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mount]
	source="matchesdb"
	destination="/mnt/matchesdb"

[env]
	DATABASE_PATH = "/mnt/name/matches.db"
